from __future__ import annotations

from typing import Any, Protocol


class LocatorLike(Protocol):
    def wait_for(self, *, state: str = "visible", timeout: float | None = None) -> None: ...
    def count(self) -> int: ...
    @property
    def first(self) -> "LocatorLike": ...
    def click(self, *args: Any, **kwargs: Any) -> None: ...
    def fill(self, value: str, *args: Any, **kwargs: Any) -> None: ...
    def input_value(self, *args: Any, **kwargs: Any) -> str: ...
    def inner_text(self, *args: Any, **kwargs: Any) -> str: ...
    def evaluate(self, expression: str, arg: Any = None) -> Any: ...
    def press(self, key: str, *args: Any, **kwargs: Any) -> None: ...
    def press_sequentially(self, text: str, *args: Any, **kwargs: Any) -> None: ...
    def select_option(self, value: str, *args: Any, **kwargs: Any) -> Any: ...


class PageLike(Protocol):
    url: str

    def locator(self, selector: str) -> LocatorLike: ...
    def evaluate(self, expression: str, arg: Any = None) -> Any: ...
    def wait_for_timeout(self, timeout: float) -> None: ...
    def screenshot(self, *args: Any, **kwargs: Any) -> bytes: ...
    @property
    def keyboard(self) -> Any: ...
